---
- name: get uname -r
  command: uname -r
  register: uname
  changed_when: false

- name: install AUFS
  apt: name={{ item }} state=present
  with_items:
   - linux-image-extra-{{ uname.stdout }}

- name: get public key for Docker
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: add Docker debian14 server to the list of servers
  copy: src=ubuntu14_docker.list dest=/etc/apt/sources.list.d/docker.list
  when:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_major_version == "14"

- name: add Docker debian15 server to the list of servers
  copy: src=ubuntu15_docker.list dest=/etc/apt/sources.list.d/docker.list
  when:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_major_version == "15"

- name: add Docker debian16 server to the list of servers
  copy: src=ubuntu16_docker.list dest=/etc/apt/sources.list.d/docker.list
  when:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_major_version == "16"

- name: update debian packages
  apt: update_cache=true
  ignore_errors: True

- name: install docker
  apt: name={{ item }} state=present
  with_items:
   - docker-engine

- name: start docker service
  service: name=docker state=started

- name: start docker service on reboot
  shell: update-rc.d docker defaults
  ignore_errors: True

- name: reboot
  shell: reboot
  when: "{{ reboot_machine }}"
