# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 256
    vb.cpus = 1
  end

  # config.ssh.insert_key = false
  # config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/ubuntu/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      apt-get -y install python-simplejson
    SHELL
  end

  config.vm.define "app1" do |app|
    app.vm.hostname = "app1.dev"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  config.vm.define "app2" do |app|
    app.vm.hostname = "app2.dev"
    app.vm.network :private_network, ip: "192.168.60.5"
  end

  config.vm.define "db" do |app|
    app.vm.hostname = "db.dev"
    app.vm.network :private_network, ip: "192.168.60.6"
  end

end
